module LocalLibrary.Greetings.SampleData where

import LocalLibrary.Greetings.API (Greeting (Greeting))

greetings :: [Greeting]
greetings =
  [ Greeting "en" "Hello, world!"
  , Greeting "fr" "Bonjour, monde!"
  , Greeting "es" "¡Hola, mundo!"
  , Greeting "de" "Hallo, Welt!"
  , Greeting "it" "Ciao, mondo!"
  , Greeting "pt" "Olá, mundo!"
  , Greeting "ru" "Привет, мир!"
  , Greeting "ja" "こんにちは世界!"
  , Greeting "ko" "안녕하세요 세계!"
  , Greeting "zh" "你好，世界！"
  , Greeting "ar" "مرحبا بالعالم!"
  , Greeting "he" "שלום עולם!"
  , Greeting "hi" "नमस्ते दुनिया!"
  , Greeting "bn" "ওহে বিশ্ব!"
  , Greeting "pa" "ਹੈਲੋ ਵਰਲਡ!"
  , Greeting "ta" "ஹலோ வேர்ல்ட்!"
  , Greeting "te" "హలో వరల్డ్!"
  , Greeting "ml" "ഹലോ വേൾഡ്!"
  , Greeting "th" "สวัสดีชาวโลก!"
  , Greeting "vi" "Xin chào thế giới!"
  , Greeting "id" "Halo dunia!"
  , Greeting "ms" "Hai dunia!"
  , Greeting "tr" "Merhaba dünya!"
  , Greeting "nl" "Hallo wereld!"
  , Greeting "pl" "Witaj świecie!"
  , Greeting "hu" "Helló Világ!"
  , Greeting "cs" "Ahoj světe!"
  , Greeting "sk" "Ahoj svet!"
  , Greeting "uk" "Привіт Світ!"
  , Greeting "ro" "Salut Lume!"
  , Greeting "bg" "Здравей свят!"
  , Greeting "el" "Γειά σου Κόσμε!"
  , Greeting "fa" "سلام دنیا!"
  , Greeting "ur" "ہیلو دنیا!"
  , Greeting "ne" "नमस्कार संसार!"
  , Greeting "mr" "नमस्कार जग!"
  , Greeting "gu" "હેલો વર્લ્ડ!"
  , Greeting "kn" "ಹಲೋ ವರ್ಲ್ಡ್!"
  ]
